apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compute-node-hpa
  namespace: edge-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ems-a
  minReplicas: 1
  maxReplicas: 4 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # CPU >50% → scale
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70   # Memory >70% → scale
